stages:
    - test
    - build-server

unit-test:
  stage: test
  image: rust:1.57
  before_script:
    - rustup default nightly
    - cargo --version
    - rustc --version;
  script:
    - cargo test --verbose

build-server-master:
  stage: build-server
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG"
    - docker tag "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE/server:latest"
    - docker push "$CI_REGISTRY_IMAGE/server:latest"
  only:
    - main

build-server:
  stage: build-server
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG"
  except:
    - main
