---
apiVersion: v1
kind: Service
metadata:
  name: avalanche-server
  namespace: avalanche
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: avalanche-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-server
  namespace: avalanche
  labels:
    app: avalanche-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanche-server
  template:
    metadata:
      labels:
        app: avalanche-server
    spec:
      containers:
        - name: avalanche-server
          image: ghcr.io/sethitow/avalanche-server:main
          env:
          - name: GIN_MODE
            value: release
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
