name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v2
      with:
        name: avalanche_server
        path: target/release/avalanche_server
